### ISSUE TITLE
Question regarding library speed

### ISSUE THREAD

**Issue by Juanvulcano** [huandu/facebook#48]
Hi there, I was wondering about the reasons there is no Oauth2 support and if there was any speed issue on a long-term rate. For example, if I wanted to get 1million get requests I think that with the current library I would have to submit the access token for each request, am I right?
How bad is this?

**Comment by huandu** [comment]
I don't quite understand your issue. Once you get a valid access token from facebook, you can use it repeatedly for months. There is no need for you to go through OAuth2 process more than once.

I decide not to integrate OAuth2 in this library because there are several awesome OAuth2 libraries and nearly all of them can work with this library well. You can read this [sample to integrate golang OAuth2 library](https://github.com/huandu/facebook#work-with-package-golangorgxoauth2).
